### ISSUE TITLE
3D rendering broken in Firefox

### ISSUE THREAD

**Issue by torokati44** [bbycroft/llm-viz#15]
See:
![image](https://github.com/bbycroft/llm-viz/assets/288816/8715545e-981f-49e1-b39c-96be94c346cc)

Looks okay in Chrome.

**Comment by bbycroft** [comment]
That's an interesting one! Could you take a screenshot of this page https://webglreport.com/?v=2 in your Firefox with the issue? Could be any combination of hardware/software/config that's causing the issue. At least, it works fine for me in my Firefox browser.

**Comment by torokati44** [comment]
Sure:
![image](https://github.com/bbycroft/llm-viz/assets/288816/fa82af04-9ba3-4834-8e6e-3309872f2dc3)

**Comment by timthelion** [comment]
Works for me on firefox:

![image](https://github.com/bbycroft/llm-viz/assets/1391608/e0e1f36f-ec35-402d-a9a0-93cdfca1a953)

**Comment by timthelion** [comment]
Weird, I'm on linux with firefox with the same GPU and it works.

```
timothy@nixos ~> uname -a
Linux nixos 6.1.55 #1-NixOS SMP PREEMPT_DYNAMIC Sat Sep 23 09:11:13 UTC 2023 x86_64 GNU/Linux
timothy@nixos ~> firefox --version
Mozilla Firefox 118.0.1
timothy@nixos ~>
```
I'm on stock kernel with no extra drivers.

**Comment by timthelion** [comment]
Only difference is your firefox is a bit newer than mine...

**Comment by torokati44** [comment]
Hmh, on a different machine, with different hardware, on FF 121, it works fine indeed. Could have been a driver issue or something like that. Thanks for checking, and for the amazing project!
